### PR TITLE
Adds lilly to the repo from juliacon-2021 GPU workshop

### PR DESCRIPTION
**Pull request by ashwani-rathee**
Adds lilly's image to the TestImages.jl repository

@jpsamaroo wants this to be CC BY NC SA 4

I made couple of changes:
- renamed lilly_hat.jpg to lilly.jpg
- cropped image to make it 1:1
- resize from 3064*3064(initially was more in one direction) to 512:512

Final image that we are adding:

If we aren't okay with any of above changes, please do mention!

### CODE REVIEW

**Review by johnnychen94 — APPROVED** [review]
I just saw the discussion on slack.

**Comment by mkitti** [comment]
It might be better if we created a Zenodo record for the repository and then linked to that.

**Review by timholy — APPROVED** [review]
It's high time that dogs achieve parity with cats (see the `chelsea.png` image).

**Comment by ashwani-rathee** [comment]
I have added the zenodo record link as asked by @mkitti , Can anyone please merge?

**Pull request merged**
