### PR TITLE
Add simple_3d_ball and simple_3d_psf

### LINKED ISSUE #90: Adding a 3D image and a 3D Point Spread Function
Hey,

I was wondering whether I could add another 3D image and a 3D point spread function (PSF) to the module?

I'm referring to this [image](https://github.com/roflmaostc/DeconvOptim.jl/blob/master/examples/obj.tif) and this [PSF](https://github.com/roflmaostc/DeconvOptim.jl/blob/master/examples/psf.tif).

For me it would be very helpful!

Thanks,

Felix

### PR DESCRIPTION
**Pull request by roflmaostc**
Closes #90 and was inspired by #93  

For the 3D ball I think it's ok to leave it like that. Do you agree?

### CODE REVIEW

**Comment by timholy** [comment]
Definitely. Most images should start out at 1. But convolution kernels are really in a different class of animal.

**Review by timholy — APPROVED** [review]

**Comment by roflmaostc** [comment]
Thanks for merging.
Is it "good practice" to set the version of OffsetArrays to 1.0?

**Comment by johnnychen94** [comment]
`OffsetArrays = "1"` means whatever version in `[1.0.0, 2.0.0]` is accepted. This package doesn't require new features in OffsetArrays, so it would be good to be `1`. This makes the Pkg version resolver happier.

Actually, `OffsetArrays = "0.9, 0.10, 0.11, 1"` would also be good.

**Comment by johnnychen94** [comment]
I'll bump the version when CI in master branch passes.

**Pull request merged**
