### PR TITLE
Test Image suitable for testing morphological operations

### LINKED ISSUE #105: [addition] Image with numbers
@johnnychen94 @timholy @zygmuntszpak Even though there are several testimages available but to show the capabilities of the algorithms implemented in ImageMorphology(which has function reference but not a separate section and the docstring is not  well developed as it is in Images.jl),I think it's good to have image with Numbers that kind of shows how mathematical morphological operations can be important in preprocessing of images in machine learning

### PR DESCRIPTION
**Pull request by ashwani-rathee**
This will be useful for morphological operations,since it has various numbers,alphabets available with foreground and background colors,also added some shapes to show erosion and dilation as it will be very clear with those,different font sizes and dotted lines are useful to show tophat and bothat functionalities
- Image is MIT License 
- Code for reproduction of Image is here: https://gist.github.com/ashwani-rathee/a835ea20bb522d35e7441978686a1951
- Name: morphology_test_512

closes #105

### CODE REVIEW

**Comment by ashwani-rathee** [comment]
Supposed to do : 
- [x] closes https://github.com/JuliaImages/TestImages.jl/issues/105

**Review by johnnychen94 — APPROVED** [review]
It looks good to me. I'll merge when you think it's stable and ready.

Would you mind uploading the TIF image? It usually has better quality than PNG image because the latter compresses the data and thus corrupted the image a little bit.

**Comment by ashwani-rathee** [comment]
Sure,I'll upload a TIF then.Image looks good to me in terms of giving a space for user to think about the result because the morphological operations depend on the input ,and with the kind of different color gradients in this image....result change greatly for even minor differences in input at least in the left half of detecting content inside images

Though no hurry to merge this one :)

**Comment by johnnychen94** [comment]
Any reason this get closed?

**Comment by ashwani-rathee** [comment]
The code with luxor isn't able to generate Tiff format, and the image is always random with current code. I'll just clean up and send a new one.

**Pull request closed without merging**
