### PR TITLE
Remove old contents from `gh-pages` branch

### PR DESCRIPTION
**Pull request by hyrodium**

### CODE REVIEW

**Comment by johnnychen94** [comment]
We need to keep CNAME and `index.html` so that old https://testimages.juliaimages.org is still available.

But we don't want the old contents, so a trick is to redirect the `index.html` to `dev/` folder. Check https://github.com/JuliaImages/juliaimages.github.io/blob/master/index.html for an example

**Comment by hyrodium** [comment]
Sorry, I was careless.
We can wait merging this PR until the next version of Documenter(v0.27.6) is released.
https://github.com/JuliaDocs/Documenter.jl/pull/1657

**Comment by johnnychen94** [comment]
Documenter  v0.27.6 actually doesn't block this PR. But I see your points, both are good to me.

**Comment by hyrodium** [comment]
I've added the `index.html` because I don't know the next release date of Documenter.jl. I've also added comment `<!--This file is automatically generated by Documenter.jl-->` in the file to be maintaned by Documenter.jl.

**Comment by johnnychen94** [comment]
And also restore the CNAME file? After that I think it's good to merge.

**Review by johnnychen94 — APPROVED** [review]

**Pull request merged**
