### PR TITLE
Fix warnings in Julia v0.7

### PR DESCRIPTION
**Pull request by juliohm**
Clean up deprecation warnings...

### CODE REVIEW

**Comment by juliohm** [comment]
Restarting the build...

**Comment by juliohm** [comment]
Can someone please clarify why GitHub is mentioning a conflicting change? I have changed the `runtests.jl` file and it was untouched in the master branch.

**Comment by timholy** [comment]
I'd be extremely surprised if this change actually does anything. `using X, Y, Z` is the same as putting all of them on separate lines.

**Comment by andreasnoack** [comment]
I suspect that you haven't had the lastest master locally when fixing these warnings since they were already fixed. Hence the only thing left here is some reformatting so I think this should just be closed.

**Comment by juliohm** [comment]
I'll check the PR again when I have access to my computer. I fixed the
warnings on a dev version (master branch) yesterday after a clone on Julia
v0.7

**Comment by timholy** [comment]
In any event this PR isn't doing anything, so let's close and you can submit a fresh one if there are still issues.

**Comment by juliohm** [comment]
Oh yes, now I see something happened when I resolved the conflicts on GitHub. It eliminated my initial commit that fixed warnings with the outdated usage of `info` from Base. I will submit a new PR.

**Pull request closed without merging**
