### PR TITLE
Adds resolution_test_1920.tif and resolution_test_512.tif to the repository

### PR DESCRIPTION
**Pull request by roflmaostc**

### CODE REVIEW

**Comment by johnnychen94** [comment]
Does this image have a clear origin or license?

**Comment by roflmaostc** [comment]
Yeah, I asked Kai Wicker personally. That image is/was used in a research group.
Maybe I should add [this link](https://www.osapublishing.org/oe/abstract.cfm?uri=oe-21-2-2032) to the metadata?

**Review by johnnychen94 — APPROVED** [review]
Yes, a reference can be helpful for future issues.

**Comment by roflmaostc** [comment]
Added the reference.

**Comment by timholy** [comment]
Good idea, thanks!

**Comment by roflmaostc** [comment]
According to the manual "maintainers will then create a tag v*-artifacts".
I have to wait for that, right?

**Comment by roflmaostc** [comment]
Thanks for creating the tag.
However, the last url was ``https://github.com/JuliaImages/TestImages.jl/releases/download/v1.2.0-artifacts/images.tar.gz``
The new one (v1.3.0) is broken.

**Comment by johnnychen94** [comment]
Sorry, there was a mess up here; I forgot the exact steps that needed to be done after new images are added. It's a new CI system and this is the first time using it.

**Comment by roflmaostc** [comment]
Now it seems to work and I created a PR to master.

**Pull request merged**
