### PR TITLE
Add simplistic 3D image and 3D PSF

### PR DESCRIPTION
**Pull request by roflmaostc**
Hey,

already discussed in #90. Is it ok like this?

We can modify `TestImages.jl` (after merging) like @timholy suggested, right?

Thanks,

Felix

### CODE REVIEW

**Comment by johnnychen94** [comment]
The names `test_3d` and `psf_3d` are too opaque here; we should use some unique names for them.

**Comment by roflmaostc** [comment]
I suspected that, any ideas for better naming?

We could probably exclude the PSF since I'm working on a function for that.

For the object: _simple_object_3D_?

**Comment by johnnychen94** [comment]
I don't know the background of the images, but `test_3d` looks like a 3d ball to me so perhaps `simple_3d_ball` and `simple_3d_ball_psf`


`mosaicview(img, nrow=8, rowmajor=true)`

image

**Comment by roflmaostc** [comment]
Yeah, your suggestion makes sense. However, the PSF has nothing to do with the ball (except same size).
I changed it to `simple_3d_psf` because it is the point spread function of a circular aperture and was computed it a naive way

**Review by johnnychen94 — APPROVED** [review]

**Comment by timholy** [comment]
Thanks!

**Comment by roflmaostc** [comment]
Thanks for merging!

I'll add the missing steps (and the special axis handling) tomorrow.

**Pull request merged**
